# Generated by Django 4.1.4 on 2023-01-10 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'get_latest_by': ['created_at'], 'ordering': ['-created_at']},
        ),
    ]
