# Generated by Django 4.1.4 on 2023-01-27 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ['-created_at'], 'ordering': ['-created_at']},
        ),
    ]
