# Generated by Django 4.1.4 on 2023-02-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=5)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.CheckConstraint(check=models.Q(('rate__gte', 1), ('rate__lte', 5)), name='rate value is valid between 1 and 5'),
        ),
    ]
